#!/usr/bin/env bash
# Install the clock-warped runsc as a containerd runtime handler on every node of
# a KinD cluster, then register a RuntimeClass. Run on the HOST (macOS/Linux)
# where `docker` and `kubectl` see the kind cluster.
#
# Node mutation is docker cp + systemctl restart containerd, so it needs no
# privileged pod and stays clear of a disallow-privileged admission policy.
#
#   ./inject-warp-runtime.sh                 # multiplier 86400 (1 day/sec)
#   MULTIPLIER=1000 ./inject-warp-runtime.sh # 1000x
#
# Requires k8s-lab/bin/{runsc-warp,containerd-shim-runsc-v1} from build-warp-runtime.sh.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLUSTER="${KIND_CLUSTER_NAME:-kind}"
MULTIPLIER="${MULTIPLIER:-86400}"
BIN="$HERE/bin"

[[ -x "$BIN/runsc-warp" && -x "$BIN/containerd-shim-runsc-v1" ]] || {
  echo "missing binaries in $BIN — run build-warp-runtime.sh in the Lima VM first" >&2
  exit 1
}

# kind node containers are named "<cluster>-control-plane", "<cluster>-worker", ...
mapfile -t NODES < <(docker ps --format '{{.Names}}' | grep "^${CLUSTER}-" || true)
[[ ${#NODES[@]} -gt 0 ]] || { echo "no kind nodes for cluster '$CLUSTER' (is it running?)" >&2; exit 1; }

# containerd runtime handler + runsc config carrying the multiplier flag.
runsc_toml="$(mktemp)"
cat > "$runsc_toml" <<EOF
# Generated by inject-warp-runtime.sh. The shim turns each [runsc_config] key
# into a --key=value runsc flag, so timewarp-multiplier reaches the patched flag.
[runsc_config]
platform = "systrap"
timewarp-multiplier = "$MULTIPLIER"
EOF

handler_toml="$(mktemp)"
cat > "$handler_toml" <<'EOF'

# --- timewarp clock-warp runtime (added by inject-warp-runtime.sh) ---
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runsc]
  runtime_type = "io.containerd.runsc.v1"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runsc.options]
    TypeUrl = "io.containerd.runsc.v1.options"
    ConfigPath = "/etc/containerd/runsc.toml"
    BinaryName = "/usr/local/bin/runsc-warp"
EOF

for node in "${NODES[@]}"; do
  echo "==> $node: installing runsc-warp + shim"
  docker cp "$BIN/runsc-warp" "$node:/usr/local/bin/runsc-warp"
  docker cp "$BIN/containerd-shim-runsc-v1" "$node:/usr/local/bin/containerd-shim-runsc-v1"
  docker exec "$node" chmod +x /usr/local/bin/runsc-warp /usr/local/bin/containerd-shim-runsc-v1
  docker cp "$runsc_toml" "$node:/etc/containerd/runsc.toml"

  # Append the runtime handler once (idempotent).
  if ! docker exec "$node" grep -q 'containerd.runtimes.runsc\]' /etc/containerd/config.toml; then
    docker cp "$handler_toml" "$node:/tmp/runsc-handler.toml"
    docker exec "$node" sh -c 'cat /tmp/runsc-handler.toml >> /etc/containerd/config.toml'
  fi

  echo "==> $node: restarting containerd"
  docker exec "$node" systemctl restart containerd
done

rm -f "$runsc_toml" "$handler_toml"

echo "==> Registering RuntimeClass 'runsc-warp'"
kubectl apply -f "$HERE/runtimeclass.yaml"

echo
echo "Done. runsc-warp is installed at ${MULTIPLIER}x on: ${NODES[*]}"
echo "Point a pod at it with:  runtimeClassName: runsc-warp"
echo "Note: the multiplier is baked into the node's runsc.toml; re-run with a new"
echo "MULTIPLIER to change it (restarts containerd)."
