#!/usr/bin/env bash
# Install the clock-warped runsc as a containerd runtime handler on every node of
# a KinD cluster, then register a RuntimeClass. Run on the HOST (macOS/Linux)
# where `docker` and `kubectl` see the kind cluster.
#
# Node mutation is docker cp + systemctl restart containerd, so it needs no
# privileged pod and stays clear of a disallow-privileged admission policy.
#
#   ./inject-warp-runtime.sh                 # multiplier 86400 (1 day/sec)
#   MULTIPLIER=1000 ./inject-warp-runtime.sh # 1000x
#
# Requires k8s-lab/bin/{runsc-warp,containerd-shim-runsc-v1} from build-warp-runtime.sh.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLUSTER="${KIND_CLUSTER_NAME:-kind}"
MULTIPLIER="${MULTIPLIER:-86400}"
TEMPORAL_MULTIPLIER="${TEMPORAL_MULTIPLIER:-30}"   # second handler for the Temporal server + worker
TIMEWARP_DELAY="${TIMEWARP_DELAY:-10s}"   # clocks run at 1x for this long after boot
BIN="$HERE/bin"

[[ -x "$BIN/runsc-warp" && -x "$BIN/containerd-shim-runsc-v1" ]] || {
  echo "missing binaries in $BIN — run build-warp-runtime.sh in the Lima VM first" >&2
  exit 1
}

# kind node containers are named "<cluster>-control-plane", "<cluster>-worker", ...
NODES=()
while IFS= read -r n; do [[ -n "$n" ]] && NODES+=("$n"); done \
  < <(docker ps --format '{{.Names}}' | grep "^${CLUSTER}-" || true)   # macOS bash 3.2 has no mapfile
[[ ${#NODES[@]} -gt 0 ]] || { echo "no kind nodes for cluster '$CLUSTER' (is it running?)" >&2; exit 1; }

# Two containerd runtime handlers, each with its own runsc config carrying the
# multiplier flag: "runsc" at $MULTIPLIER and "runsc-temporal" at $TEMPORAL_MULTIPLIER.
# The shim turns each [runsc_config] key into a --key=value runsc flag.
runsc_toml() {  # $1 = multiplier
  cat <<EOF
# Generated by inject-warp-runtime.sh.
binary_name = "/usr/local/bin/runsc-warp"
[runsc_config]
platform = "systrap"
timewarp-multiplier = "$1"
timewarp-delay = "$TIMEWARP_DELAY"
EOF
}
handler_toml() {  # $1 = handler name, $2 = config path
  cat <<EOF

# --- timewarp clock-warp runtime "$1" (added by inject-warp-runtime.sh) ---
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.$1]
  runtime_type = "io.containerd.runsc.v1"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.$1.options]
    TypeUrl = "io.containerd.runsc.v1.options"
    ConfigPath = "$2"
    BinaryName = "/usr/local/bin/runsc-warp"
EOF
}

for node in "${NODES[@]}"; do
  echo "==> $node: installing runsc-warp + shim"
  docker cp "$BIN/runsc-warp" "$node:/usr/local/bin/runsc-warp"
  docker cp "$BIN/containerd-shim-runsc-v1" "$node:/usr/local/bin/containerd-shim-runsc-v1"
  runsc_toml "$MULTIPLIER"          | docker exec -i "$node" sh -c 'cat > /etc/containerd/runsc.toml'
  runsc_toml "$TEMPORAL_MULTIPLIER" | docker exec -i "$node" sh -c 'cat > /etc/containerd/runsc-temporal.toml'
  # docker cp keeps the host uid/mode; make the binaries root-owned and executable.
  # The runsc symlink is a fallback for shims that ignore binary_name.
  docker exec "$node" sh -c 'chown root:root /usr/local/bin/runsc-warp /usr/local/bin/containerd-shim-runsc-v1 \
    && chmod 755 /usr/local/bin/runsc-warp /usr/local/bin/containerd-shim-runsc-v1 \
    && ln -sf /usr/local/bin/runsc-warp /usr/local/bin/runsc'

  # Append each handler once (idempotent). Piped over stdin: docker cp into the
  # node's tmpfs /tmp is silently lost.
  for h in runsc:/etc/containerd/runsc.toml runsc-temporal:/etc/containerd/runsc-temporal.toml; do
    name="${h%%:*}"; cfg="${h#*:}"
    if ! docker exec "$node" grep -q "containerd.runtimes.${name}\]" /etc/containerd/config.toml; then
      handler_toml "$name" "$cfg" | docker exec -i "$node" sh -c 'cat >> /etc/containerd/config.toml'
    fi
  done

  echo "==> $node: restarting containerd"
  docker exec "$node" systemctl restart containerd
done

echo "==> Registering RuntimeClasses runsc-warp and runsc-warp-temporal"
kubectl apply -f "$HERE/runtimeclass.yaml"

echo
echo "Done. runsc-warp (${MULTIPLIER}x) and runsc-warp-temporal (${TEMPORAL_MULTIPLIER}x) installed on: ${NODES[*]}"
echo "Point a pod at one with:  runtimeClassName: runsc-warp | runsc-warp-temporal"
echo "Note: the multiplier is baked into the node's runsc.toml; re-run with a new"
echo "MULTIPLIER to change it (restarts containerd)."
